[theme]
primaryColor = "#FF4500"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true